### ISSUE TITLE
uk.ac.shef.dcs.jate.JATEException: Cannot find expected field: jate_ngraminfo

### ISSUE THREAD

**Issue by jerrygaoLondon** [ziqizhang/jate#22]
JATEException when executing AppChiSquare for ACL RD-TEC corpus. Meanwhile, it fails to shutdown threads cleanly which causes main thread hangs.

```
2016-02-07 22:53:05 ERROR FrequencyCtxSentenceBasedFBWorker:89 - Unable to build feature for document id:6996
uk.ac.shef.dcs.jate.JATEException: Cannot find expected field: jate_ngraminfo
	at uk.ac.shef.dcs.jate.util.SolrUtil.getTermVector(SolrUtil.java:35)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.computeSingleWorker(FrequencyCtxSentenceBasedFBWorker.java:67)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.computeSingleWorker(FrequencyCtxSentenceBasedFBWorker.java:22)
	at uk.ac.shef.dcs.jate.JATERecursiveTaskWorker.compute(JATERecursiveTaskWorker.java:38)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:969)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2004)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:713)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:54)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:22)
	at uk.ac.shef.dcs.jate.JATERecursiveTaskWorker.compute(JATERecursiveTaskWorker.java:36)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:969)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2004)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:713)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:54)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:22)
	at uk.ac.shef.dcs.jate.JATERecursiveTaskWorker.compute(JATERecursiveTaskWorker.java:36)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

2016-02-07 22:53:06 ERROR FrequencyCtxSentenceBasedFBWorker:89 - Unable to build feature for document id:7015
uk.ac.shef.dcs.jate.JATEException: Cannot find expected field: jate_ngraminfo
	at uk.ac.shef.dcs.jate.util.SolrUtil.getTermVector(SolrUtil.java:35)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.computeSingleWorker(FrequencyCtxSentenceBasedFBWorker.java:67)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.computeSingleWorker(FrequencyCtxSentenceBasedFBWorker.java:22)
	at uk.ac.shef.dcs.jate.JATERecursiveTaskWorker.compute(JATERecursiveTaskWorker.java:38)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:969)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2004)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:713)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:54)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:22)
	at uk.ac.shef.dcs.jate.JATERecursiveTaskWorker.compute(JATERecursiveTaskWorker.java:36)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:969)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2004)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:713)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:54)
	at uk.ac.shef.dcs.jate.feature.FrequencyCtxSentenceBasedFBWorker.mergeResult(FrequencyCtxSentenceBasedFBWorker.java:22)
	at uk.ac.shef.dcs.jate.JATERecursiveTaskWorker.compute(JATERecursiveTaskWorker.java:36)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jerrygaoLondon** [comment]
the problem has been identified that documents with empty content was indexed which cause the exception. A workaround is to avoid indexing of empty documents.
