### ISSUE TITLE
Error creating core [GENIA]: Function not implemented

### ISSUE THREAD

**Issue by jerrygaoLondon** [ziqizhang/jate#23]
15:25:58 ERROR CoreContainer:740 - Error creating core [ACLRDTEC]: Function not implemented
15:25:58 ERROR CoreContainer:740 - Error creating core [GENIA]: Function not implemented

```
Exception in thread "main" org.apache.solr.common.SolrException: SolrCore 'ACLRDTEC' is not available due to init failure: Function not implemented
        at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:978)
        at uk.ac.shef.dcs.jate.app.App.extract(App.java:268)
        at uk.ac.shef.dcs.jate.app.AppATTF.main(AppATTF.java:51)
Caused by: org.apache.solr.common.SolrException: Function not implemented
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:820)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:659)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:727)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:447)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:438)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Function not implemented
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1082)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
        at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:114)
        at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
        at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
        at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:94)
        at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4508)
        at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:524)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:761)
        ... 9 more
```

**Comment by jerrygaoLondon** [comment]
The problem happens in cloud server and can be resolved by configuring correct Lucene LockFactory for NFS environment. In NFS, we should set lock type to "simple": <lockType>${solr.lock.type:simple}</lockType> in solrconfig.xml.

See more details in https://lucene.apache.org/core/3_0_3/api/core/org/apache/lucene/store/NativeFSLockFactory.html.
