### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException in OpenNLPPOSTaggerFilter

### ISSUE THREAD

**Issue by jerrygaoLondon** [ziqizhang/jate#25]
Exception throws out when indexing documents.

This happens when replacing JATE customized tokeniser with Solr standard tokeniser and charFilter for irregular text in jate_text_2_terms analyser chain.

```
2016-03-06 00:49:08 ERROR SolrCore:139 - org.apache.solr.common.SolrException: Exception writing document id A00-1002_cln.xml to the index; possible analysis error.
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:167)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:955)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1110)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:706)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:250)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:177)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:98)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:74)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2068)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:174)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:139)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:153)
	at uk.ac.shef.dcs.jate.util.JATEUtil.addNewDoc(JATEUtil.java:292)
	at uk.ac.shef.dcs.jate.app.ACLRDTECTest.indexJATEDocuments(ACLRDTECTest.java:164)
	at uk.ac.shef.dcs.jate.app.ACLRDTECTest.indexAndExtract(ACLRDTECTest.java:127)
	at uk.ac.shef.dcs.jate.app.AppATEACLRDTECTest.main(AppATEACLRDTECTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 18
	at java.lang.String.<init>(String.java:199)
	at org.apache.lucene.analysis.jate.OpenNLPPOSTaggerFilter.walkTokens(OpenNLPPOSTaggerFilter.java:81)
	at org.apache.lucene.analysis.jate.OpenNLPPOSTaggerFilter.incrementToken(OpenNLPPOSTaggerFilter.java:45)
	at org.apache.lucene.analysis.jate.OpenNLPMWEFilter.walkTokens(OpenNLPMWEFilter.java:267)
	at org.apache.lucene.analysis.jate.OpenNLPRegexChunker.incrementToken(OpenNLPRegexChunker.java:53)
	at org.apache.lucene.analysis.core.LowerCaseFilter.incrementToken(LowerCaseFilter.java:45)
	at org.apache.lucene.analysis.jate.EnglishLemmatisationFilter.incrementToken(EnglishLemmatisationFilter.java:30)
	at org.apache.lucene.analysis.util.FilteringTokenFilter.incrementToken(FilteringTokenFilter.java:51)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:613)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1475)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:163)
	... 25 more
```

**Comment by jerrygaoLondon** [comment]
bug cause by using solr.StandardTokenizerFactory which don't lack of payload information required by regexChunker; fix the issue to make it work
